Add "MySQLMessageTypeMapper" for storing mappings into long-lasting storage.
UltimateSoftware/camunda-message-streaming pull request #35
Opened 2021-02-03 14:58 UTC by LeoZ100

2021-02-03 15:22 UTC, dare2try commented on messaging/src/main/java/com/ultimatesoftware/workflow/messaging/topicmapping/entities/ExtensionData.java
> +
Extra line break

2021-02-03 16:18 UTC, ChrisFlanTheMan requested changes

2021-02-03 16:18 UTC, ChrisFlanTheMan commented on messaging/src/main/java/com/ultimatesoftware/workflow/messaging/topicmapping/MySqlMessageTypeMapper.java
> +        ExtensionData extensionData = new ExtensionData();
any reason why we are creating a new extension data object, rather than just saving the one we were given? Also rather than calling the setter, its better to create a new constructor that takes in tenantId and messageTypeExtensionData.

2021-02-03 16:18 UTC, ChrisFlanTheMan commented on messaging/src/main/java/com/ultimatesoftware/workflow/messaging/topicmapping/entities/ExtensionData.java
> +    public void setData(String tenantId, MessageTypeExtensionData messageTypeExtensionData) {
this should be a constructor imo

2021-02-03 16:27 UTC, LeoZ100 commented on messaging/src/main/java/com/ultimatesoftware/workflow/messaging/topicmapping/MySqlMessageTypeMapper.java
> +        ExtensionData extensionData = new ExtensionData();
`ExtensionData` is the entity for the database and we're given a `MessageTypeExtensionData` which is the object used by the library, we're converting from one to the other. Not sure if Spring will let you use the original object as an entity. Agree on the constructor 👍 .

2021-02-04 15:57 UTC, ChrisFlanTheMan approved these changes

2021-02-04 16:11 UTC, ChrisFlanTheMan requested changes

2021-02-04 16:11 UTC, ChrisFlanTheMan commented on messaging/pom.xml
> +		<version>0.2.5.6-SNAPSHOT</version>
this is NOT a valid version. Remember that version follows the format: {major}.{minor}.{patch}. And sometimes with the -SNAPSHOT. You should never have 4 numbers here. Please fix this.

2021-02-04 17:54 UTC, ChrisFlanTheMan approved these changes

2021-02-04 18:11 UTC, merged